// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC08B },
    { 3, 0xC65B },
    { 3, 0xCB9C },
    { 3, 0xD0D8 },
    { 3, 0xD5F0 }
};

#define TITLE_BIN                       0
#define ENDING_BIN                      1
#define LEVEL0C_BIN                     2
#define LEVEL1C_BIN                     3
#define MARCO_BIN                       4

