// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.0 20200202
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xC9FA },
    { 3, 0xD397 },
    { 3, 0xDC4F },
    { 3, 0xE505 },
    { 3, 0xED77 },
    { 3, 0xF5B3 },
    { 4, 0xC000 },
    { 4, 0xC75D },
    { 4, 0xCE33 },
    { 4, 0xD509 },
    { 4, 0xDB81 },
    { 4, 0xE1F1 },
    { 4, 0xE85E },
    { 4, 0xEEB2 },
    { 4, 0xF4BA },
    { 6, 0xC000 },
    { 4, 0xFAB4 },
    { 6, 0xC59A },
    { 3, 0xFD9C },
    { 3, 0xFF25 }
};

#define LEVEL0C_BIN                     0
#define LEVEL4C_BIN                     1
#define LEVEL2C_BIN                     2
#define LEVEL1C_BIN                     3
#define ZONEA_BIN                       4
#define LEVEL3C_BIN                     5
#define ZONEB_BIN                       6
#define INTRO7_BIN                      7
#define INTRO5_BIN                      8
#define INTRO6_BIN                      9
#define INTRO2_BIN                      10
#define ENDING_BIN                      11
#define INTRO4_BIN                      12
#define INTRO3_BIN                      13
#define INTRO1_BIN                      14
#define DEDICADO_BIN                    15
#define TITLE_BIN                       16
#define LOGO_BIN                        17
#define CONTROLS_BIN                    18
#define MARCO_BIN                       19
#define LEVEL_SCREEN_TSC_BIN            20

