// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.0 20200202
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xC9D7 },
    { 3, 0xD357 },
    { 3, 0xDBE8 },
    { 3, 0xE470 },
    { 3, 0xECE9 },
    { 3, 0xF517 },
    { 4, 0xC000 },
    { 4, 0xC77D },
    { 4, 0xCE6F },
    { 4, 0xD559 },
    { 4, 0xDBF0 },
    { 4, 0xE26B },
    { 4, 0xE8DF },
    { 4, 0xEF4F },
    { 4, 0xF577 },
    { 6, 0xC000 },
    { 4, 0xFB71 },
    { 6, 0xC5B8 },
    { 3, 0xFD07 },
    { 3, 0xFE90 }
};

#define LEVEL0C_BIN                     0
#define LEVEL4C_BIN                     1
#define LEVEL2C_BIN                     2
#define LEVEL1C_BIN                     3
#define ZONEA_BIN                       4
#define LEVEL3C_BIN                     5
#define ZONEB_BIN                       6
#define INTRO7_BIN                      7
#define INTRO5_BIN                      8
#define INTRO6_BIN                      9
#define INTRO2_BIN                      10
#define INTRO4_BIN                      11
#define INTRO3_BIN                      12
#define ENDING_BIN                      13
#define INTRO1_BIN                      14
#define DEDICADO_BIN                    15
#define TITLE_BIN                       16
#define LOGO_BIN                        17
#define CONTROLS_BIN                    18
#define MARCO_BIN                       19
#define LEVEL_SCREEN_TSC_BIN            20

