// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by ene2h.exe from ..\enems\enems.ene
// Copyleft 2010, 2017 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char x1, y1, x2, y2;
	char mx, my;
	char t;
#ifdef PLAYER_CAN_FIRE
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0
 	{16, 16, 16, 16, 16, 128, 0, 1, 1},
 	{64, 32, 64, 32, 80, 128, 2, 2, 2},
 	{128, 32, 128, 32, 112, 112, -2, 2, 3},
 	{160, 32, 160, 32, 208, 32, 1, 0, 2},
 	{128, 128, 128, 128, 128, 48, 0, -1, 4},
 	{208, 128, 208, 128, 160, 128, -1, 0, 1},

	// Pantalla 1
 	{48, 0, 48, 0, 80, 32, 1, 1, 1},
 	{96, 0, 96, 0, 112, 32, 2, 2, 2},
 	{160, 0, 160, 0, 144, 32, -2, 2, 3},
 	{208, 80, 208, 80, 208, 112, 0, 2, 1},
 	{192, 96, 192, 96, 192, 128, 0, 2, 2},
 	{144, 64, 144, 64, 128, 128, -2, 2, 3}

};

#define N_ENEMS_TYPE_0 0
#define N_ENEMS_TYPE_1 4
#define N_ENEMS_TYPE_2 4
#define N_ENEMS_TYPE_3 3
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 0

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{0, 0, 0}, 
	{167, 1, 0}
};

#define N_HOTSPOTS_TYPE_0 1
#define N_HOTSPOTS_TYPE_1 1
#define N_HOTSPOTS_TYPE_2 0
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

